---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fm-deployment
  labels:
    k8s-app: fmaster
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: fmaster
  template:
    metadata:
      labels:
        k8s-app: fmaster
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: fzzmaster
        image: 172.20.12.114:5000/afl-llvm:latest
        command: ['afl-fuzz'] 
        args: ['-i', '/opt/seed', '-o', 'sync_dir', '-M', '$(HOSTNAME)' ,'/opt/aflpng/libpng/.libs/pngtest','@@']
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        securityContext:
          privileged: true

        volumeMounts: 
        - mountPath: "/sync_dir"
          name: image-store
      volumes:
      - name: image-store
        persistentVolumeClaim:
          claimName: cephfs-pvc
          readOnly: false
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fms-deployment
  labels:
    k8s-app: fslave
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: fslave
  template:
    metadata:
      labels:
        k8s-app: fslave
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: fzzslave
        image: 172.20.12.114:5000/afl-llvm:latest
        command: ['afl-fuzz'] 
        args: ['-i', '/opt/seed', '-o', 'sync_dir', '-S', '$(HOSTNAME)' ,'/opt/aflpng/libpng/.libs/pngtest','@@']
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        securityContext:
          privileged: true

        volumeMounts: 
        - mountPath: "/sync_dir"
          name: image-store
      volumes:
      - name: image-store
        persistentVolumeClaim:
          claimName: cephfs-pvc
          readOnly: false
---
